# Generated by Django 5.0.4 on 2024-05-01 18:27

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_question_name_alter_quiz_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='name',
            field=django_ckeditor_5.fields.CKEditor5Field(),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='name',
            field=django_ckeditor_5.fields.CKEditor5Field(),
        ),
    ]
